title: The one and only amazing title
author: Carlos C.
email: carlosc@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description for this includes: Testing a change of (1) Title, (2) Author, (3) Email, and lastly (4) Description

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
